name: Upload Hexasweeper Version From Tag

on:
  push:
    tags:
      - 'v?[0-9]+\.[0-9]+.*'

  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_publish:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitppc:latest
      options: --cpus 1

    permissions:
      contents: write

    env:
      VERSION_MATCH_REGEX: 'v?([0-9]+\.[0-9]+\.[0-9])'

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # TODO: Get latest release tag, not the master branch.
    - name: Clone GRRLIB
      uses: actions/checkout@master
      with:
        repository: GRRLIB/GRRLIB
        ref: master
        path: grrlib/

    - name: Build & Install GRRLIB
      working-directory: grrlib/
      run: |
            make -C GRRLIB clean all install 
    
    - name: Build Hexasweeper
      run: make build

    - name: OpenShopChannel creation dependencies
      run:
        apt install -y xmlstarlet

    - name: Creating OpenShopChannel version
      run: |
          mkdir -p osc-tar/apps/hexaswiiper/

          cp hexaswiiper.dol osc-tar/apps/hexaswiiper/boot.dol
          cp data/Logo1.png osc-tar/apps/hexaswiiper/icon.png

          xmlstarlet edit --update "/app/version" --value ${{github.ref_name}} --update "/app/release_date" --value $(date "+%F") osc-meta.xml.tmpl > osc-tar/apps/hexaswiiper/meta.xml

          tar -f hexaswiiper-osc.tar -C osc-tar/ -c .

    # Create the GitHub release.
    - name: Release on GitHub.
      uses: softprops/action-gh-release@v2
      with:
        name: "Version ${{github.ref_name}}"
        generate_release_notes: true
        files: |
            hexaswiiper.dol
            hexaswiiper.elf
            hexaswiiper-osc.tar
        make_latest: true
